require("abhiruk.set")
require("abhiruk.remap")
require("abhiruk.lazy_init")
vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("colorscheme gruvbox")
require("telescope").load_extension('harpoon')
vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
